# -*- coding: utf-8 -*-
"""series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBTjDLRH9d0xZJOSBHrEnABwHwIqg3_4
"""

import pandas as pd
ser=pd.Series([10,20,30,4,60])
ser

ser2=pd.Series([i for i in range(10,50)],index=[i*i for i in range(10,50)])
ser2

ser3=pd.Series([i for i in range(1,5)],index=['a','b','c','d'])
ser3

ser3.loc[["a","b"]]

ser3.loc['a':'d']